export const supermarketItems = [
  "Apples",
  "Bananas",
  "Oranges",
  "Grapes",
  "Lemons",
  "Strawberries",
  "Blueberries",
  "Pineapple",
  "Mango",
  "Peaches",
  "Watermelon",
  "Cantaloupe",
  "Avocados",
  "Tomatoes",
  "Potatoes",
  "Onions",
  "Carrots",
  "Broccoli",
  "Spinach",
  "Lettuce",
  "Kale",
  "Cucumbers",
  "Bell peppers",
  "Zucchini",
  "Eggplant",
  "Mushrooms",
  "Garlic",
  "Ginger",
  "Sweet potatoes",
  "Green beans",
  "Asparagus",
  "Cauliflower",
  "Celery",
  "Peas",
  "Corn",
  "Corn on the cob",
  "Cabbage",
  "Brussels sprouts",
  "Radishes",
  "Beets",
  "Squash",
  "Butternut squash",
  "Pumpkin",
  "Yams",
  "Tofu",
  "Almond milk",
  "Cow's milk",
  "Soy milk",
  "Rice milk",
  "Cheese",
  "Yogurt",
  "Butter",
  "Cream cheese",
  "Ice cream",
  "Frozen pizza",
  "Frozen vegetables",
  "Frozen berries",
  "Frozen fries",
  "Frozen chicken nuggets",
  "Frozen fish",
  "Frozen seafood",
  "Frozen meals",
  "Bread",
  "Whole wheat bread",
  "Sourdough bread",
  "Bagels",
  "Croissants",
  "English muffins",
  "Tortillas",
  "Crackers",
  "Chips",
  "Granola bars",
  "Cereal",
  "Oatmeal",
  "Pancake mix",
  "Maple syrup",
  "Honey",
  "Peanut butter",
  "Jam",
  "Nutella",
  "Coffee",
  "Tea",
  "Juice",
  "Soda",
  "Bottled water",
  "Sports drinks",
  "Beer",
  "Wine",
  "Spirits",
  "Condiments",
  "Salad dressing",
  "Spices",
  "Pasta",
  "Rice",
  "Lentils",
  "Canned beans",
  "Canned vegetables",
  "Canned fruit",
  "Canned soup",
  "Baking supplies",
];
